### ISSUE TITLE
Install/audit gives some warnings

### ISSUE THREAD

**Issue by kerrpeter** [akhi-ninja/oruga-vue3-starter#4]
yarn install gives some info and warning messages, would be nice to know we're starting with no warnings

info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@vue/cli-plugin-unit-jest > vue-jest@3.0.7" has incorrect peer dependency "vue@^2.x".
warning "@vue/cli-plugin-unit-jest > vue-jest@3.0.7" has unmet peer dependency "vue-template-compiler@^2.x".
warning " > vue-jest@5.0.0-alpha.10" has unmet peer dependency "@babel/core@7.x".
warning " > vue-jest@5.0.0-alpha.10" has unmet peer dependency "babel-jest@>= 24 < 27".
warning " > vue-jest@5.0.0-alpha.10" has unmet peer dependency "jest@>= 24 < 27 ".

Also yarn audit reports

60 vulnerabilities found - Packages audited: 1762
Severity: 57 Moderate | 3 High

**Comment by akhi-ninja** [comment]
@kerrpeter  the 3 high  vulnerabilities  are from vue-cli , 
https://snyk.io/test/npm/@vue/cli

https://github.com/vuejs/vue-cli/issues/6375 , i have used latest stable version of the package , since its under devDependencies , we can ignore , it will not affect production . I will update the package when ever the stable version is ready
